### PR TITLE
Basic test coverage

### LINKED ISSUE #10: Test coverage
Library and the demo app should contain a bunch of unit and instrumentation test to prevent regression.

Setup for this is ready with our CircleCI implementation.

### PR DESCRIPTION
**Pull request by LukasPaczos**
Closes #10.

### CODE REVIEW

File: library/src/test/java/com/mapbox/android/gestures/AndroidGesturesManagerTest.java [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+
+    mutuallyExclusivesList.add(set1);
+    mutuallyExclusivesList.add(set2);
+    mutuallyExclusivesList.add(set3);
+
+    androidGesturesManager =
+      new AndroidGesturesManager(
+        RuntimeEnvironment.application.getApplicationContext(),
+        mutuallyExclusivesList);
+  }
```
Comment (tobrun) [inline library/src/test/java/com/mapbox/android/gestures/AndroidGesturesManagerTest.java]: this setup method will be called for each test found in `AndroidGesturesManagerTest`, this means if you would add more tests to this class the set1,set2,set3 will grow equally to the amount of tests. I think you want to recreate the lists with each `@Before`

File: library/src/test/java/com/mapbox/android/gestures/MultiFingerTapGestureDetectorTest.java [hunk 2]
```diff
@@ -0,0 +1,184 @@
...
+    MockitoAnnotations.initMocks(this);
+    multiFingerTapGestureDetector = Mockito.spy(new MultiFingerTapGestureDetector(context, androidGesturesManager));
+    multiFingerTapGestureDetector.setListener(listener);
+    doReturn(true).when(multiFingerTapGestureDetector).checkPressure();
+    doReturn(false).when(multiFingerTapGestureDetector).isSloppyGesture();
+  }
+
+  @Test
+  public void twoFingerTapTest() {
+    dispatchMultiFingerTap(false);
```
Comment (tobrun) [inline library/src/test/java/com/mapbox/android/gestures/MultiFingerTapGestureDetectorTest.java]: this kind of test feels weird. a test mostly reads like:

```
@Test
public void testSomething(){
  Object expected = {something};
  Object actual = {something};
   assertEquals(expected, actual);
}
```

a test should assert if something is equal, verify if a mocked object is called and that should be obvious from the test code itself. Don't worry about repeating code, that is allowed with tests.

File: library/src/test/java/com/mapbox/android/gestures/AbstractGestureDetectorTest.java [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+import java.lang.reflect.ParameterizedType;
+
+@RunWith(RobolectricTestRunner.class)
+public abstract class AbstractGestureDetectorTest<K extends BaseGesture<L>, L> {
+  AndroidGesturesManager androidGesturesManager;
+  Context context;
+  MotionEvent emptyMotionEvent;
+
+  K gestureDetector;
+  L listener;
```
Comment (tobrun) [inline library/src/test/java/com/mapbox/android/gestures/AbstractGestureDetectorTest.java]: missing access modifiers on above? can be protected?
